language: node_js
<<<<<<< HEAD
node_js:
  - "0.11"
  - "0.10"
script:
  - npm test
=======

sudo: false

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@^3.3.0

script:
  - gulp lint
  - gulp test:ci
  - mocha test/
  - npm run-script codecov
>>>>>>> refs/remotes/michael/master
